import RevHalt.Trilemma.CofinalHornsSimple

namespace RevHalt.Trilemma

universe u
variable {PropT : Type u} {Code : Type u}

section DynamicPA

-- 1) Context variables (same as CofinalHornsSimple)
variable (Provable : Set PropT -> PropT -> Prop)
variable (K : RHKit)
variable (Machine : Code -> Trace)
variable (encode_halt : Code -> PropT)
variable (Cn : Set PropT -> Set PropT)
variable (A0 : ThState (PropT := PropT) Provable Cn)

-- 2) The explicit sigma
variable (sigma : Nat -> Mode)

-- 3) Definition: PA is "in" the state Gamma (Explicit PAax)
def PA_in (PAax : Set PropT) (Γ : Set PropT) : Prop :=
  ∀ p, p ∈ PAax → p ∈ Γ

-- 4) Witnesses and Hypotheses
variable (hIdem : CnIdem Cn) (hProvCn : ProvClosedCn Provable Cn)
variable (witBC : CofinalWitness (Pair (Provable := Provable) (K := K) (Machine := Machine)
          (encode_halt := encode_halt) (Cn := Cn) (A0 := A0) hIdem hProvCn .BC))
variable (witAC : CofinalWitness (Pair (Provable := Provable) (K := K) (Machine := Machine)
          (encode_halt := encode_halt) (Cn := Cn) (A0 := A0) hIdem hProvCn .AC))
variable (witAB : CofinalWitness (Pair (Provable := Provable) (K := K) (Machine := Machine)
          (encode_halt := encode_halt) (Cn := Cn) (A0 := A0) hIdem hProvCn .AB))

/--
Hypothesis (HPA): PA is present cofinally along the 'times' subsequence determined by the witnesses.
This captures "Dynamic PA" -- Peano Arithmetic reappears arbitarily often in the history
generated by the interaction. Using CofinalK to denote this happens for cofinally many phases k.
-/
def CofinalPA_along_times (PAax : Set PropT) : Prop :=
  CofinalK (fun k =>
    let t := times (Provable := Provable) (K := K) (Machine := Machine)
             (encode_halt := encode_halt) (Cn := Cn) (A0 := A0)
             sigma hIdem hProvCn witBC witAC witAB k
    PA_in PAax (chainState Provable K Machine encode_halt Cn hIdem hProvCn A0 t).Γ
  )

/--
The "Dynamic Disjunctive Totality" Theorem (Weak Bundle version).

If the modes are visited cofinally by `sigma`, and PA is visited cofinally (Dynamic PA),
then we observe each of the three Trilemma Horns cofinally, alongside PA cofinally.

This establishes that Peano Arithmetic (as a recurring property) is compatible with
the global structural instability of the Trilemma.
-/
theorem dynamic_trilemma_with_PA
    (PAax : Set PropT)
    (hMono : ProvRelMonotone Provable)
    (hCnExt : CnExtensive Cn)
    (hBC : SigmaCofinal sigma .BC)
    (hAC : SigmaCofinal sigma .AC)
    (hAB : SigmaCofinal sigma .AB)
    (hPA : CofinalPA_along_times Provable K Machine encode_halt Cn A0 sigma hIdem hProvCn witBC witAC witAB PAax) :
    (CofinalN (HornBC_at_time Provable K Machine encode_halt Cn A0 sigma hIdem hProvCn witBC witAC witAB)) ∧
    (CofinalN (HornAC_at_time Provable K Machine encode_halt Cn A0 sigma hIdem hProvCn witBC witAC witAB)) ∧
    (CofinalN (HornAB_at_time Provable K Machine encode_halt Cn A0 sigma hIdem hProvCn witBC witAC witAB)) ∧
    (CofinalPA_along_times Provable K Machine encode_halt Cn A0 sigma hIdem hProvCn witBC witAC witAB PAax) := by
  refine ⟨?_, ?_, ?_, hPA⟩
  · exact cofinal_hornBC_along_times Provable K Machine encode_halt Cn A0 sigma hMono hCnExt hIdem hProvCn witBC witAC witAB hBC
  · exact cofinal_hornAC_along_times Provable K Machine encode_halt Cn A0 sigma hMono hCnExt hIdem hProvCn witBC witAC witAB hAC
  · exact cofinal_hornAB_along_times Provable K Machine encode_halt Cn A0 sigma hMono hCnExt hIdem hProvCn witBC witAC witAB hAB

end DynamicPA

end RevHalt.Trilemma
